nameOverride: "prefect-worker-local-k3s"
fullnameOverride: "prefect-worker-local-k3s"
worker:
  apiConfig: selfHostedServer

  selfHostedServerApiConfig:
    apiUrl: "https://prefect.plusai.is/api"
    basicAuth:
      enabled: false
  image:
    repository: prefecthq/prefect
    prefectTag: "3.6.22-python3.13-kubernetes"
    pullPolicy: IfNotPresent

  config:
    workPool: "k3s-ssdnodes"
    type: "kubernetes"
    installPolicy: "never"
    queryInterval: 10
    prefetchSeconds: 10
    http2: true
    limit: 5

  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 4
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80

  livenessProbe:
    enabled: true
    config:
      initialDelaySeconds: 30
      periodSeconds: 20
      timeoutSeconds: 5
      failureThreshold: 3
      successThreshold: 1

  resources:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      cpu: "1"
      memory: 1Gi

  podAnnotations: {}
  podLabels:
    app.kubernetes.io/part-of: prefect

  affinity: {}
  tolerations: []

  extraEnvVarsSecrets: 
    - prefect-worker

serviceAccount:
  create: true
  name: "prefect-worker-local-k3s"

role:
  create: true
  namespace: prefect
  extraPermissions: 
   - apiGroups: [""]
     resources: ["pods", "services"]
     verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

rolebinding:
  create: true