# values-prefect-worker-gke-autopilot-cloudrunv2.yaml

worker:
  apiConfig: selfHostedServer

  selfHostedServerApiConfig:
    apiUrl: "http://prefect-server.prefect.svc.cluster.local:4200/api"
    basicAuth:
      enabled: false
  image:
    repository: prefecthq/prefect-gcp
    prefectTag: "0.6.17-python3.13"
    pullPolicy: IfNotPresent

  config:
    workPool: "gcr-pool"
    type: "cloud-run-v2"
    installPolicy: "never"
    queryInterval: 10
    prefetchSeconds: 10
    http2: true
    limit: 5

  replicaCount: 2
  podDisruptionBudget:
    minAvailable: 1

  livenessProbe:
    enabled: true
    config:
      initialDelaySeconds: 30
      periodSeconds: 20
      timeoutSeconds: 5
      failureThreshold: 3
      successThreshold: 1

  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      cpu: "1"
      memory: 1Gi

  autoscaling:
    enabled: false

  podAnnotations: {}
  podLabels:
    app.kubernetes.io/part-of: prefect

  affinity: {}
  tolerations: []

serviceAccount:
  create: true
  name: "prefect-worker"
  annotations:
    iam.gke.io/gcp-service-account: "prefect-worker@prefect-automation-490317.iam.gserviceaccount.com"

# cloud-run-v2 场景下通常不需要这套 Kubernetes RBAC
role:
  create: false

rolebinding:
  create: false