worker:
  config:
    baseJobTemplate:
      configuration: |
        {
          "variables": {
            "type": "object",
            "properties": {
              "cpu": {
                "type": "string",
                "title": "CPU",
                "default": "1000m",
                "description": "The CPU to allocate to the Cloud Run job."
              },
              "env": {
                "type": "object",
                "title": "Environment Variables",
                "default": {
                  "PREFECT_API_URL": "https://prefect.plusai.is/api"
                },
                "description": "Environment variables to set when starting a flow run.",
                "additionalProperties": {
                  "anyOf": [
                    {
                      "type": "string"
                    },
                    {
                      "type": "null"
                    }
                  ]
                }
              },
              "args": {
                "type": "array",
                "items": {
                  "type": "string"
                },
                "title": "Args",
                "description": "The arguments to pass to the Cloud Run Job V2's entrypoint command."
              },
              "name": {
                "anyOf": [
                  {
                    "type": "string"
                  },
                  {
                    "type": "null"
                  }
                ],
                "title": "Name",
                "default": "cp-cloud-run-v2",
                "description": "Name given to infrastructure created by a worker."
              },
              "image": {
                "anyOf": [
                  {
                    "type": "string"
                  },
                  {
                    "type": "null"
                  }
                ],
                "title": "Image Name",
                "default": "prefecthq/prefect:3.6.28-python3.13",
                "description": "The image to use for the Cloud Run job. If not provided the default Prefect image will be used."
              },
              "labels": {
                "type": "object",
                "title": "Labels",
                "description": "Labels applied to infrastructure created by a worker.",
                "additionalProperties": {
                  "type": "string"
                }
              },
              "memory": {
                "type": "string",
                "title": "Memory",
                "default": "512Mi",
                "pattern": "^\\d+(?:G|Gi|M|Mi)$",
                "examples": [
                  "512Mi"
                ],
                "description": "The memory to allocate to the Cloud Run job along with the units, whichcould be: G, Gi, M, Mi."
              },
              "region": {
                "type": "string",
                "title": "Region",
                "default": "us-west1",
                "description": "The region in which to run the Cloud Run job"
              },
              "command": {
                "anyOf": [
                  {
                    "type": "string"
                  },
                  {
                    "type": "null"
                  }
                ],
                "title": "Command",
                "description": "The command to use when starting a flow run. In most cases, this should be left blank and the command will be automatically generated by the worker."
              },
              "timeout": {
                "type": "integer",
                "title": "Job Timeout",
                "default": 600,
                "maximum": 86400,
                "description": "Max allowed time duration the Job may be active before Cloud Run will  actively try to mark it failed and kill associated containers (maximum of 86400 seconds, 1 day).",
                "exclusiveMinimum": 0
              },
              "keep_job": {
                "type": "boolean",
                "title": "Keep Job After Completion",
                "default": false,
                "description": "Keep the completed Cloud run job on Google Cloud Platform."
              },
              "credentials": {
                "$ref": "#/definitions/GcpCredentials",
                "title": "GCP Credentials",
                "description": "The GCP Credentials used to connect to Cloud Run. If not provided credentials will be inferred from the local environment."
              },
              "max_retries": {
                "type": "integer",
                "title": "Max Retries",
                "default": 0,
                "description": "The number of times to retry the Cloud Run job."
              },
              "launch_stage": {
                "enum": [
                  "ALPHA",
                  "BETA",
                  "GA",
                  "DEPRECATED",
                  "EARLY_ACCESS",
                  "PRELAUNCH",
                  "UNIMPLEMENTED",
                  "LAUNCH_TAG_UNSPECIFIED"
                ],
                "type": "string",
                "title": "Launch Stage",
                "default": "BETA",
                "description": "The launch stage of the Cloud Run Job V2. See https://cloud.google.com/run/docs/about-features-categories for additional details."
              },
              "env_from_secrets": {
                "type": "object",
                "title": "Environment Variables from Secrets",
                "default": {
                  "PREFECT_CLIENT_CUSTOM_HEADERS": {
                    "secret": "PREFECT_CF_HEADER",
                    "version": "latest"
                  }
                },
                "examples": [
                  {
                    "ENV_VAR_NAME": {
                      "secret": "SECRET_NAME",
                      "version": "latest"
                    }
                  }
                ],
                "description": "Environment variables to set from GCP secrets when starting a flow run.",
                "additionalProperties": {
                  "$ref": "#/definitions/SecretKeySelector"
                }
              },
              "cloudsql_instances": {
                "anyOf": [
                  {
                    "type": "array",
                    "items": {
                      "type": "string"
                    }
                  },
                  {
                    "type": "null"
                  }
                ],
                "title": "Cloud SQL Instances",
                "examples": [
                  "project:region:instance-id"
                ],
                "description": "List of Cloud SQL instance connection names to connect to. Format: {project}:{location}:{instance}"
              },
              "vpc_connector_name": {
                "anyOf": [
                  {
                    "type": "string"
                  },
                  {
                    "type": "null"
                  }
                ],
                "title": "VPC Connector Name",
                "description": "The name of the VPC connector to use for the Cloud Run job."
              },
              "service_account_name": {
                "anyOf": [
                  {
                    "type": "string"
                  },
                  {
                    "type": "null"
                  }
                ],
                "title": "Service Account Name",
                "default": "prefect-worker@prefect-automation-490317.iam.gserviceaccount.com",
                "examples": [
                  "service-account@example.iam.gserviceaccount.com"
                ],
                "description": "The name of the service account to use for the task execution of Cloud Run Job. By default Cloud Run jobs run as the default Compute Engine Service Account."
              },
              "prefect_api_key_secret": {
                "anyOf": [
                  {
                    "$ref": "#/definitions/SecretKeySelector"
                  },
                  {
                    "type": "null"
                  }
                ],
                "title": "Prefect API Key Secret",
                "examples": [
                  {
                    "secret": "prefect-api-key",
                    "version": "latest"
                  }
                ],
                "description": "The GCP secret to use for the Prefect API key. When provided, the secret will be used instead of the PREFECT_API_KEY environment variable."
              },
              "prefect_api_auth_string_secret": {
                "anyOf": [
                  {
                    "$ref": "#/definitions/SecretKeySelector"
                  },
                  {
                    "type": "null"
                  }
                ],
                "title": "Prefect API Auth String Secret",
                "examples": [
                  {
                    "secret": "prefect-api-auth-string",
                    "version": "latest"
                  }
                ],
                "description": "The GCP secret to use for the Prefect API auth string. When provided, the secret will be used instead of the PREFECT_API_AUTH_STRING environment variable."
              }
            },
            "definitions": {
              "GcpCredentials": {
                "type": "object",
                "title": "GcpCredentials",
                "properties": {
                  "project": {
                    "anyOf": [
                      {
                        "type": "string"
                      },
                      {
                        "type": "null"
                      }
                    ],
                    "title": "Project",
                    "default": null,
                    "description": "The GCP project to use for the client."
                  },
                  "service_account_file": {
                    "anyOf": [
                      {
                        "type": "string",
                        "format": "path"
                      },
                      {
                        "type": "null"
                      }
                    ],
                    "title": "Service Account File",
                    "default": null,
                    "description": "Path to the service account JSON keyfile."
                  },
                  "service_account_info": {
                    "anyOf": [
                      {
                        "type": "object",
                        "additionalProperties": true
                      },
                      {
                        "type": "null"
                      }
                    ],
                    "title": "Service Account Info",
                    "default": null,
                    "description": "The contents of the keyfile as a dict."
                  }
                },
                "description": "Block used to manage authentication with GCP. Google authentication is\nhandled via the `google.oauth2` module or through the CLI.\nSpecify either one of service `account_file` or `service_account_info`; if both\nare not specified, the client will try to detect the credentials following Google's\n[Application Default Credentials](https://cloud.google.com/docs/authentication/application-default-credentials).\nSee Google's [Authentication documentation](https://cloud.google.com/docs/authentication#service-accounts)\nfor details on inference and recommended authentication patterns.",
                "secret_fields": [
                  "service_account_info.*"
                ],
                "block_type_slug": "gcp-credentials",
                "block_schema_references": {}
              },
              "SecretKeySelector": {
                "type": "object",
                "title": "SecretKeySelector",
                "required": [
                  "secret",
                  "version"
                ],
                "properties": {
                  "secret": {
                    "type": "string",
                    "title": "Secret"
                  },
                  "version": {
                    "type": "string",
                    "title": "Version"
                  }
                },
                "description": "SecretKeySelector is a data model for specifying a GCP secret to inject\ninto a Cloud Run V2 Job as an environment variable.\nFollows Cloud Run V2 rest API, docs:\nhttps://cloud.google.com/run/docs/reference/rest/v2/Container#SecretKeySelector"
              }
            },
            "description": "Default variables for the v2 Cloud Run worker.\n\nThe schema for this class is used to populate the `variables` section of the\ndefault base job template."
          },
          "job_configuration": {
            "env": "{{ env }}",
            "name": "{{ name }}",
            "labels": "{{ labels }}",
            "region": "{{ region }}",
            "command": "{{ command }}",
            "timeout": "{{ timeout }}",
            "job_body": {
              "client": "prefect",
              "template": {
                "template": {
                  "timeout": "{{ timeout }}",
                  "vpcAccess": {
                    "connector": "{{ vpc_connector_name }}"
                  },
                  "containers": [
                    {
                      "env": [],
                      "args": "{{ args }}",
                      "image": "{{ image }}",
                      "command": "{{ command }}",
                      "resources": {
                        "limits": {
                          "cpu": "{{ cpu }}",
                          "memory": "{{ memory }}"
                        }
                      }
                    }
                  ],
                  "maxRetries": "{{ max_retries }}",
                  "serviceAccount": "{{ service_account_name }}"
                }
              },
              "launchStage": "{{ launch_stage }}"
            },
            "keep_job": "{{ keep_job }}",
            "credentials": "{{ credentials }}",
            "env_from_secrets": "{{ env_from_secrets }}",
            "cloudsql_instances": "{{ cloudsql_instances }}",
            "prefect_api_key_secret": "{{ prefect_api_key_secret }}",
            "prefect_api_auth_string_secret": "{{ prefect_api_auth_string_secret }}"
          }
        }